name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        fail-fast: false
        configuration: [Debug, ExportDebug, ExportRelease]

    runs-on: ubuntu-latest

    env:
      Solution_Name: Godot Module/WebRTC Match Maker Godot Module.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: DotNet Restore
      run: dotnet restore
      working-directory: Godot Module/

    - name: DotNet Build
      run: dotnet build --configuration ${{ matrix.Configuration }}
      working-directory: Godot Module/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Godot Module
        path: Godot Module/.godot/mono/temp/bin
