name: Rust Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        rust-channel: ["stable", "beta", "nightly", "1.76.0", "1.75.0", "1.74.0", "1.73.0", "1.72.1", "1.72.0", "1.71.1", "1.71.0", "1.70.0", "1.69.0", "1.68.2", "1.68.1", "1.68.0", "1.67.1", "1.67.0", "1.66.1", "1.66.0", "1.65.0", "1.64.0", "1.63.0", "1.62.1", "1.62.0", "1.61.0", "1.60.0"]
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: |
        rustup install ${{ matrix.rust-channel }}
        rustup show
        rustup --version
        cargo +${{ matrix.rust-channel }} --version
        rustc +${{ matrix.rust-channel }} --version
    
    - name: Debug Build
      run: cargo build
      working-directory: Match Maker Server/
      
    - name: Release Build
      run: cargo build --release
      working-directory: Match Maker Server/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Match Maker Server
        path: Match Maker Server/target/
